#! /bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor setup
bspc monitor -d I II III IV V VI VII VIII IX X

# Visuals
bspc config border_width		2
bspc config window_gap			8
#bspc config top_padding			-8

bspc config focused_border_color	\#FC935C
bspc config presel_feedback_color	\#FC935C

bspc config split_ratio         	0.50
bspc config borderless_monocle  	true
bspc config gapless_monocle     	false

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a '*:*:Picture-in-Picture' state=floating
